### ISSUE TITLE
Verificar mínimamente que los documentos subidos en la convocatoria son válidos

### ISSUE THREAD

**Issue by apiad** [matcom/pncti#2]
Verificar al menos que los documentos son el formato de archivo correcto.
Idealmente, verificar algún elemento de contenido (o metadatos) que indique que es la plantilla que fue descargada del sitio.

> ¿Es posible poner algo en los metadatos de las plantillas que podamos verificar después?

**Comment by manuelAW99** [comment]
Bueno, las bib python-docx y openpyxl extraen metadatos, ahí hay cosas como la fecha de creación que es un datetime o el nombre del autor que podemos comprobar

**Comment by apiad** [comment]
@manuelAW99 Eso me cuadra, implica modificar los documentos de plantilla para inyectarle ese metadato

**Comment by manuelAW99** [comment]
@apiad voy a usar el campo keywords (por coger uno), y por ahora los voy a identificar con su nombre.

- Anexo 1: anexo1

**Comment by apiad** [comment]
@manuelAW99 👍👍
